train_dirs:
  - dataset/train
val_dirs:
  - dataset/val
num_classes: 3             # 因为只有一个类别 "pig"
batch_size: 4
num_epochs: 50             # 10 太少了，50-100 比较合理
learning_rate: 0.001
model_dir: models
negative_dir: dataset/negative   # 如果有负样本，写上


# 应用配置
minio:
  url: http://119.96.28.202:8094
  accessKey: huangshiMinio
  secretKey: huangshiMinioPsswordIs@9527
  bucketName: huangshi-mini